send_learned_ir_command:
  target:
    entity:
      domain: remote
      integration: tuya_local
  fields:
    command:
      required: true
      example: "Play"
      selector:
        object:
    device:
      example: "TV"
      selector:
        text:
    emitter_entity_id:
      example: "infrared.my_ir_emitter"
      required: true
      selector:
        entity:
          filter:
            domain: infrared

save_meal_plan:
  target:
    entity:
      domain: calendar
      integration: tuya_local
  fields:
    name:
      required: true
      example: "Weekday"
      selector:
        text:
    force:
      example: true
      selector:
        boolean:

load_meal_plan:
  target:
    entity:
      domain: calendar
      integration: tuya_local
  fields:
    name:
      required: true
      example: "Weekday"
      selector:
        text:

delete_meal_plan:
  target:
    entity:
      domain: calendar
      integration: tuya_local
  fields:
    name:
      required: true
      example: "Weekday"
      selector:
        text:
